### ISSUE TITLE
Fix the iOS repo for Mercury

### ISSUE THREAD

**Issue by swiftcode** [CodeDoesGood/MercuryFront#11]
The repo is broken.
There are too many Pods.  We can trim down a few.

**Comment by MassimoSavinoAtKater** [comment]
I'd keep it to CocoaLumberjack, Fabric and Crashlytics at a minimum though.

**Comment by northtwilight** [comment]
I'd keep it to CocoaLumberjack, Fabric and Crashlytics at a minimum though.

**Comment by swiftcode** [comment]
Began the fix.  I am looking into which repos we want to keep.

**Comment by swiftcode** [comment]
This issue is being closed because it's not on the correct repo and because the mobile versions will be WebViews of the Web app.
